### ISSUE TITLE
Upgrade to MongoDB 3.0 compatible driver.

### ISSUE THREAD

**Issue by adunkman** [NodeDC/node-dc-irc#4]
On October 3rd, MongoLab upgraded our sandbox account to use Mongo 3.0. Great! 

Except that we were using an out of date version of the Node driver, which meant that we lost connectivity (with the helpful error message of “auth failed”). 

I did a quick push just now to upgrade the driver version, but it’s a major version change and I haven’t looked into the API changes. It doesn’t work — we’ll need to figure out what changed in the mongo driver from 1.4.10 to 2.0.45 (8cd7e7374f9970b0aceca43fb2ed732c3734fe5c).

**Comment by adunkman** [comment]
Oh, almost forgot the log: 

```
2015-10-05T18:28:26.940192+00:00 heroku[router]: at=info method=GET path="/messages" host=node-dc-irc.herokuapp.com request_id=3b6f93d6-e5cc-48b4-828d-970d53a3fbf7 fwd="73.163.195.114" dyno=web.1 connect=1ms service=3285ms status=500 bytes=640
2015-10-05T18:28:26.923288+00:00 app[web.1]: Debug: hapi, internal, implementation, error 
2015-10-05T18:28:26.923292+00:00 app[web.1]:     TypeError: Cannot read property 'collectionName' of undefined
2015-10-05T18:28:26.923294+00:00 app[web.1]:     at mongoCursorOperationProxy (/app/node_modules/newrelic/lib/instrumentation/mongodb.js:125:41)
2015-10-05T18:28:26.923296+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/newrelic/node_modules/continuation-local-storage/context.js:74:17)
2015-10-05T18:28:26.923297+00:00 app[web.1]:     at wrapSegmentInvocation [as toArray] (/app/node_modules/newrelic/lib/transaction/tracer.js:262:63)
2015-10-05T18:28:26.923299+00:00 app[web.1]:     at /app/lib/mongodb.js:52:12
2015-10-05T18:28:26.923307+00:00 app[web.1]:     at cb_callbackProxy (/app/node_modules/newrelic/lib/instrumentation/mongodb.js:318:39)
2015-10-05T18:28:26.923308+00:00 app[web.1]:     at /app/node_modules/newrelic/node_modules/continuation-local-storage/context.js:74:17
2015-10-05T18:28:26.923309+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
2015-10-05T18:28:26.923311+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:1920:5
2015-10-05T18:28:26.923313+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
2015-10-05T18:28:26.923314+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/db.js:283:5
```
